### ISSUE TITLE
Feature request and question

### ISSUE THREAD

**Issue by MilosStanic** [bradmartin/nativescript-drawingpad#1]
Hi, 

I'm considering using NativeScript 2.0 for an app.

So my first question (that may be a stupid one): is this plugin compatible with NativeScript 2.0?

And the feature request, as my app should be multilingual, can you somehow allow plugin users to specify the label on buttons instead of "Get Drawing" and "Clear Drawing"?

Thanks.

**Comment by bradmartin** [comment]
Hi, this plugin is compatible. Just FYI NativeScript 2.0 isn't a rewrite but just a new version so mostly everything is the same from previous versions. Just tons of new features.

As for the buttons that's just the demo for this. You can do whatever you want in your app. The buttons can have whatever text you like :smile:

**Comment by MilosStanic** [comment]
Sorry for dumb questions, I'm a n00b for NativeScript. Coming from Angular + Meteor world. 
Thanks for your work.

**Comment by bradmartin** [comment]
All good, no dumb questions 👍 . If you aren't on the slack community for NativeScript, you should join. Really great community committed to seeing it continue to succeed 😄
