### ISSUE TITLE
Scaling on orientation change

### ISSUE THREAD

**Issue by hypery2k** [bradmartin/nativescript-drawingpad#10]
Is it possible to rescale the image on orientation change?
If we turn to landscape orientation we have to clear first to enforce a repaint (to fill the complete screen width) and if we go back to portrait mode the image get cuts off.

Is it possible to resize/scale the image on orientation change?

**Comment by bradmartin** [comment]
Don't think there's anything exposed by the native libs to handle this. Not
to say it can't be done but nothing very quick to add. Going from memory
here so I need to review the native libs and see to be sure. Think it's
somewhat of a challenge bc it's not an image in the actual pad area. There
is no image until you process the drawing pad. So not even sure how elegant
a native solution would be. That might be why square payments are always
locked orientation on the screen from what I've seen when using square
payment readers and stuff.

**Comment by bradmartin** [comment]
I thought this was the case but the native Android library doesn't support screen rotations, see here: https://github.com/gcacace/android-signaturepad#caveats until that is possible I don't see a way to expose that functionality here without burning a ton of time unfortunately.

**Comment by hypery2k** [comment]
thanks for investigating on this.
