### ISSUE TITLE
Enable set a background image

### ISSUE THREAD

**Issue by Daxito** [bradmartin/nativescript-drawingpad#11]
Hi, would be it be easy to add the ability of adding a background image?

**Comment by bradmartin** [comment]
The component does extension View class from NativeScript so those properties should be possible to support. The kicker is if the native libraries have limitations which I haven't looked into.

**Comment by bradmartin** [comment]
@Daxito did you try setting a background to the view?

**Comment by Daxito** [comment]
@bradmartin Right now I am working on something else, but this is something I might have to retake a look at. I did not set a background to the view, if I do that, would my annotations be permanent on the image? I actually need to modify the images by drawing on them then save them.

**Comment by bradmartin** [comment]
yea... don't think that will work as it is. I don't think the native libs expected that as a use case so it's likely not possible with their implementation. Might be something I look into in the future but no time right now.

**Comment by Daxito** [comment]
ok, just wondering, I will check other options, thank you!
