### ISSUE TITLE
Draw lost on hide element

### ISSUE THREAD

**Issue by eleddie** [bradmartin/nativescript-drawingpad#12]
I need to have different drawing areas but in the same place, so I need to hide and show the DrawingPads depending on a variable:

This is an example of the code:
`<template ngFor let-dp let-i="index" [ngForOf]="[1,2,3,4]">`
          `<DrawingPad *ngIf="i == variable" col="0" height="200" id="drawingPad-{{i}}" penColor="#000" penWidth="3"></DrawingPad>`
`</template>`

But if I draw something in Pad#1, change to Pad#2 (which is empty, as expected) and the back to Pad#1, the Pad#1 is empty... I need them to keep what was drawn.

Any ideas how to achieve this?

**Comment by bradmartin** [comment]
I've not gotten into angular2 yet. Is there another alternative to ngIf, my
guess is that's removing it from the tree, but I don't know. Have you tried
just setting the visibility=false when you want to hide one from the view?
Another option might be to animate it out of the screen and adjust the
opacity so it's not visible and then bring it back.

**Comment by eleddie** [comment]
I think it might be loosing the reference and when it shows again it creates a new reference. Is there a way to set the value of the DrawingPad? Like when you do pad.getMyDrawing() and it returns a Promise with the image, set that image returned to a DrawingPad value

**Comment by bradmartin** [comment]
Don't think there's an easy way to take the image and back into the drawing
view. What you could do is layer an image on top of the drawing view and
put the image to the src and then draw on top of the layer.

**Comment by eleddie** [comment]
Is it possible to create the DrawingPad object programmatically and then append it to the view? That way the reference isn't lost..

**Comment by eleddie** [comment]
I just solved the problem by using `visibility: collapsed;` and `visibility: visible;` depending on the state, instead of *ngIf. Thanks for your help. I'll dig more into it to se if there's a better way.

**Comment by bradmartin** [comment]
My guess then Is that ngIf removes the view from the tree so it renders new
when added back. Or so it seems that way

**Comment by eleddie** [comment]
Yes, that might be. Thanks for your help and quick response!
