### ISSUE TITLE
clearDrawing leaves behind a misty background

### ISSUE THREAD

**Issue by thaborobotdwarf** [bradmartin/nativescript-drawingpad#13]
Hello. I am using this module on ios and every time when I call clearDrawing there is a white semitransparent background being left behind. Below is my xml: 

`<Page xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:DrawingPad="nativescript-drawingpad" loaded="pageLoaded">
    <ActionBar title="NativeScript-DrawingPad" />
    <ScrollView>
        <StackLayout id="drawingPad1">
            <DrawingPad:DrawingPad 
            tap="clearDrawing"   
            penColor="#000" 
            penWidth="50" 
            touch="coordinates"
            opacity="0.7" 
            height="400"
            style="background-color: none"
            id="drawingPad" />
         <Button text="Clear" tap="clearDrawing" />
        </StackLayout>
    </ScrollView>
</Page>`

my js file is as follows:
var page;
function pageLoaded(args) {
    page = args.object;
} 
exports.pageLoaded = pageLoaded; 
//# sourceMappingURL=main-page.js.map

exports.clearDrawing=function(){
    var drawingPad = page.getViewById('drawingPad');
   drawingPad.clearDrawing();
} 

My package.json:
`{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.helpendehandios",
    "tns-ios": {
      "version": "2.3.0"
    }
  },
  "dependencies": {
    "nativescript-screen-orientation": "^1.0.2",
    "tns-core-modules": "2.3.0"
  }
}`

**Comment by bradmartin** [comment]
@thaborobotdwarf - could you try updating your NS app to the latest release and see if it's still an issue? 
http://docs.nativescript.org/releases/upgrade-instructions#upgrading-the-nativescript-tools

**Comment by thaborobotdwarf** [comment]
Hi @bradmartin , I have done that but the issue does not go away. My package.json is as follows:
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.helpendehandios",
    "tns-ios": {
      "version": "2.4.0"
    }
  },
  "dependencies": {
    "nativescript-screen-orientation": "^1.0.2",
    "tns-core-modules": "^2.4.2"
  }
}

**Comment by bradmartin** [comment]
If someone wants to help update the cocoapod - I believe a fix was pushed to the native lib that resolves this.
