### ISSUE TITLE
Android line thickness

### ISSUE THREAD

**Issue by eleddie** [bradmartin/nativescript-drawingpad#14]
The problem is that I'm setting the pen width to 2 or even 1 and the line doesn't change the size, it is too big

**Comment by bradmartin** [comment]
Could you try the demo app on the repo and see if you get the same result? If not, could you provide a sample app to test this with? I have not seen this issue personally.

**Comment by bradmartin** [comment]
Demo app is working, if you have an issue still please share the code and I'll help you figure out what's wrong in your setup. 😄
