### ISSUE TITLE
Cast image to base64

### ISSUE THREAD

**Issue by dzfweb** [bradmartin/nativescript-drawingpad#15]
How do i cast the drawabled image into base64 string?

**Comment by bradmartin** [comment]
Use the `image-source` modules `fromNativeSource(image)` passing in the image from the promise result to get an image-source. Then use [toBase64String method](http://docs.nativescript.org/api-reference/classes/_image_source_.imagesource.html#tobase64string) on the image-source instance.

``` typescript
import * as imageSourceModule from 'image-source';

drawingPad.getDrawing().then((res) => {        
          console.log(res);
          let x = imageSourceModule.fromNativeSource(res);
          let the64string = x.toBase64String("PNG");
       });  
```

**Comment by dzfweb** [comment]
Thank you. 
It works.
👍

**Comment by steve-79** [comment]
Just in case anyone is banging their head on the wall - the above code by bradmartin worked for me on android perfectly, however iOS in Nativescript Vue needed the x.toBase64String("PNG") to be lowercase as such: x.toBase64String('png')
