### ISSUE TITLE
iOS archive failed

### ISSUE THREAD

**Issue by davorpeic** [bradmartin/nativescript-drawingpad#16]
Hi,

there seems to be issue with building app for archive, (normal build to app works fine)

```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

I tried few solutions mentioned here http://stackoverflow.com/questions/21366549/errorthe-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-res but none of them fix the issue.

- clean app with just plugin added, 
- xcode 8.3
- pod version 1.2.0

thanks

**Comment by bradmartin** [comment]
Seen this before with iOS. You have some pod issue on your machine. You'll
have to delete some pod folder on your mac and run pod init or something. I
went through it a week ago. It's not an issue with this plugin but your
local iOS setup. If I find what CMD I ran that fixed it I'll post here. It
was a rough day when I encountered it.

**Comment by davorpeic** [comment]
Hey,

yeah, I remember I lowered my cocoapods version for some other plugin issue, could be related as it is not the lates version. If I find the fix will post it too for future reference.

thanks Brad
