### ISSUE TITLE
IOS not working

### ISSUE THREAD

**Issue by loadchief** [bradmartin/nativescript-drawingpad#22]
Hi, I am able to use drawing pad successfully on android but nothing appears on the drawing pad surface on ios.  I do not get any errors and I am able to successfully dump the drawingpad object in the console.  Any suggestions?  I am using angular/typescript TNS version 2.5.2

`<GridLayout rows="160, auto" columns="*">
    
    <StackLayout row="0" col="0" class="custom-padding custom-border"> 
        <DrawingPad #drawingPad penColor="#000000" penWidth="3"></DrawingPad>
    </StackLayout>    

    <GridLayout row="1" col="0" rows="auto" columns="*, *" class="add-bar"> 
        <Button row="0" col="0" text="Save Signature" class="btn btn-primary btn-active button-bar" (tap)="savePodSignature()"></Button>
        <Button row="0" col="1" text="Cancel" class="btn btn-primary btn-active button-bar" (tap)="cancel()"></Button>
    </GridLayout> 

</GridLayout>`

`export class PodSignatureComponent implements OnInit {
   
    public showProgress: boolean;
    public progressValue: number;
    private sub: any;    
    public jobId: any;      
    public jobStatus: any; 

    public pad: any;
    @ViewChild("drawingPad") DrawingPad: ElementRef;

    public constructor( private http: Http, 
                        private route: ActivatedRoute, 
                        private router: Router, 
                        private location: Location, 
                        private api: LoadchiefAPI,
                        private headerService: HeaderService) {}    

    public ngOnInit() {

        this.sub = this.route.params.subscribe(params => {
            this.jobId = +params['jobId']; 
        });   

        this.jobStatus = 'Picked Up';   
        this.headerService.sendMessage('POD Signature');     
    }

    public ngAfterViewInit() {
        this.pad = this.DrawingPad.nativeElement;
        console.dump(this.pad);
    }`

**Comment by bradmartin** [comment]
iOS layouts sometimes require height and width. If you have no errors and
it's just not rendering that's the first thing to try. Set a static
height/width and let me know. Thanks

**Comment by loadchief** [comment]
I created a css class with a height and width property and applied that class to the stack layout that houses the <DrawingPad> element but still no response when you draw.  I also removed the other two classes on that stack layout just in case they were interfering.

**Comment by loadchief** [comment]
`<GridLayout rows="160, auto" columns="*">
    
    <StackLayout row="0" col="0" class="draw-pad"> 
        <DrawingPad #drawingPad penColor="#000000" penWidth="3"></DrawingPad>
    </StackLayout>    

    <GridLayout row="1" col="0" rows="auto" columns="*, *" class="add-bar"> 
        <Button row="0" col="0" text="Save Signature" class="btn btn-primary btn-active button-bar" (tap)="savePodSignature()"></Button>
        <Button row="0" col="1" text="Cancel" class="btn btn-primary btn-active button-bar" (tap)="cancel()"></Button>
    </GridLayout> 

</GridLayout>`

**Comment by loadchief** [comment]
![image](https://user-images.githubusercontent.com/20728482/27101009-f4f09b0c-5034-11e7-965a-3a240c8eebe0.png)

**Comment by loadchief** [comment]
![image](https://user-images.githubusercontent.com/20728482/27101173-7f589aba-5035-11e7-8c9a-a1a2de3d5759.png)

**Comment by bradmartin** [comment]
what about on the `DrawingPad` itself? nothing rendering? can you upload screens?

**Comment by loadchief** [comment]
Thank you Brad.  Yes, applying a fixed width and height directly to the DrawingPad element allows it to work / render actual drawings.
