### ISSUE TITLE
iOS SignatureView is not visible on release builds

### ISSUE THREAD

**Issue by manojdcoder** [bradmartin/nativescript-drawingpad#25]
iOS SignatureView works fine on development builds installed on device / simulator, but when making a release build the SignatureView itself is completely hidden. Please refer the screenshots below.

**Debug Build**

<img width="502" alt="debug" src="https://user-images.githubusercontent.com/4987027/30400576-f2a69a50-98f4-11e7-89df-d42804afd935.png">

**Release Build**

<img width="386" alt="release" src="https://user-images.githubusercontent.com/4987027/30400587-f8ee8026-98f4-11e7-94b2-57b1acb4ea3b.png">

Release build log for your reference.
[BuildLog.txt](https://github.com/bradmartin/nativescript-drawingpad/files/1300945/BuildLog.txt)

**Comment by prabudevarrajan1** [comment]
I am also facing the same issue. SignatureView works find in debug mode, but not in release mode

**Comment by manojdcoder** [comment]
It seems to be some issue when setting height of drawing pad component in css + webpack + uglify and not with this plugin, hence closing this issue.

**Comment by bradmartin** [comment]
Were you setting the height in CSS? Or on the element?

**Comment by bradmartin** [comment]
Makes sense. Thanks for following up with that info. I believe the plugins
can provide a file that helps prevent that from happening. I've never had
to do it but might be a good addition if someone wants to put a PR together
for it. The drop down plugin I think is a good example
