### ISSUE TITLE
Failed to find module Failed to find module: "ui/core/proxy", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by nmongiya** [bradmartin/nativescript-drawingpad#26]
After updating to "tns-android": {
      "version": "3.2.0"
    }

I think we need to update the import statements.
Although I tried to change
var view_1 = require("ui/core/view"); to
var view_1 = require("tns-core-modules/ui/core/view");

but could not find to where to find var proxy_1 = require("ui/core/proxy");

**Comment by bradmartin** [comment]
Did you update the plugin, what version do you have in your package.json?

**Comment by nmongiya** [comment]
"nativescript-drawingpad": "^1.1.2",

**Comment by bradmartin** [comment]
That's why :) you're on a version that worked prior to NS 3.0, now that you're updated on NS there were many breaking changes to the UI layer at 3.0 and the plugin had a major release for its 2.0 version to be compatible with NS3+ Try updating your plugin and rebuilding your app.

**Comment by bradmartin** [comment]
https://github.com/bradmartin/nativescript-drawingpad#installation see here

**Comment by nmongiya** [comment]
I have updated to "nativescript-drawingpad": "^2.1.0", and it is working now. Thank for your help. 👍
