### ISSUE TITLE
feature request: tap event on signature pad

### ISSUE THREAD

**Issue by paweldziura** [bradmartin/nativescript-drawingpad#29]
Sometimes you want to disable navigation buttons if signaturepad is empty. Would be cool to be able to detect if user did any action on the pad by having tapEvent on it.

**Comment by tom-it** [comment]
the promise of getDrawing will reject if drawingpad is empty, so you could just no react to the button being pressed, or display an error message?

**Comment by bradmartin** [comment]
That is a good idea, you can try to get the image on your button taps, and if it rejects then you don't have anything in the drawing area.

**Comment by JCAguilera** [comment]
I actually need the events feature, as I need to send data only when the user is drawing.
