### ISSUE TITLE
[Android] TypeError on SignaturePad

### ISSUE THREAD

**Issue by vcooley** [bradmartin/nativescript-drawingpad#31]
On Android, I am unable to use this extension due to the following type error when I try to register, then use the element in an Angular application.

```
ERROR Error: Uncaught (in promise): TypeError: Could not load view for: DrawingPad.TypeError: Cannot read property 'SignaturePad' of undefined
TypeError: Could not load view for: DrawingPad.TypeError: Cannot read property 'SignaturePad' of undefined
```

I am not referencing a property called `SignaturePad` anywhere in my application. Any clue what might cause this?

**Comment by kobi84** [comment]
The same here.

**Comment by kobi84** [comment]
I was able to fix this by executing `tns update`.
You can also try this https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/
or by moving 
`import {registerElement} from 'nativescript-angular/element-registry';
registerElement('DrawingPad', () => require('nativescript-drawingpad').DrawingPad);`
form specific component to main.ts file. In component you just use `import {DrawingPad} from 'nativescript-drawingpad';`
Hope this helps.

**Comment by bradmartin** [comment]
Demo seems to be working, @kobi84 comment should help. As the error indicates the native lib did not build into your executable.
