### ISSUE TITLE
can the drawing pad starts with an image?

### ISSUE THREAD

**Issue by slasho** [bradmartin/nativescript-drawingpad#32]
If I need to "edit" a signature can I get the old signature in order to see the old one?

thanks!

**Comment by bradmartin** [comment]
It could as a background with the drawingpad on top of it, but I don't think the image will get exported with that approach when you get the drawing through the API. There are some ways to do that on android I'm aware of, probably same for iOS just not familiar.

**Comment by isaacfi** [comment]
You can combine two bitmaps with nativescript-bitmap-factory plugin to get one, this answer shows the [Example](https://stackoverflow.com/a/41723368)
