### ISSUE TITLE
Issue with drawing pad on tns 4.0.0 (Windows machine build)

### ISSUE THREAD

**Issue by arunwrc** [bradmartin/nativescript-drawingpad#39]
[issuewithdrawingpadontns4_0_0.zip](https://github.com/bradmartin/nativescript-drawingpad/files/2012948/issuewithdrawingpadontns4_0_0.zip)

am arun from india, first of all i would like to thank your team for a wonderful plugin that you have created for public. It was working fine on nativescript 3 without any issues, but when i upgraded to tns 4, it shows some issues and begin to break the application. 

I then tried your plugin on a new instance(Angular) but no difference at all. Please do something needful.

Am attaching my package.json and error log with this mail.
Thanks and regards. Arun

**Comment by bradseefeld** [comment]
I am seeing this as well. Using nativescript 4.1 and followed setup per README. I am using Angular 5.2.

**Comment by bradseefeld** [comment]
Bah! Im still pretty new to nativescript and I keep forgetting you must remove platforms and re-add after adding a plugin.

So,

```
tns platform remove android
tns platform add android
```
will solve this 'issue'.
