### ISSUE TITLE
Missing "binaries"

### ISSUE THREAD

**Issue by orgbx** [bradmartin/nativescript-drawingpad#4]
Hi Brad,
Your plugin is not working at least with {N} 2.1
The problem is simple: your release doesn't ship the *.js files so the module is not found at run time. I guess nativescript doesn't compile node modules anymore.
My quick & dirty fix for now is this script in my package.json:
"postinstall": "cd ./node_modules/nativescript-drawingpad/ && tsc || echo \"drawing pad compiled correctly :)\""
A "prepublish" script compiling the typescript files would be awesome 👍 
Cheers and thanks for the plugin!
Omar

**Comment by bradmartin** [comment]
Oh thanks for reporting. I'll check it out. If you npm install and have no .js files I likely screwed up the publish :) so I'll fix that.

**Comment by bradmartin** [comment]
https://www.npmjs.com/package/nativescript-drawingpad fixed
