### ISSUE TITLE
Plugin makes my app crash on minimizing (Android)

### ISSUE THREAD

**Issue by JorgeHawkins** [bradmartin/nativescript-drawingpad#40]
I just installed the plugin and made some test. Up to this point, the app had shown no issues with the plugin UNTIL I minimized the app. Android threw the following exception:

`An uncaught Exception occurred on "main" thread.
java.lang.NullPointerException: Attempt to read from field 'int android.app.Fragment.mContainerId' on a null object reference
at android.app.BackStackRecord$1.onPreDraw(BackStackRecord.java:1131)
at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2000)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1084)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5990)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
at android.view.Choreographer.doCallbacks(Choreographer.java:580)
at android.view.Choreographer.doFrame(Choreographer.java:550)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5343)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)`

This exception only appears when DrawingPad is loaded via "include" into my project. 

Nativescript version:
4.0.2

DrawingPad version:
3.0.3

**Comment by bradmartin** [comment]
What do you mean by "include"? Not sure I understand how you're using it.
Can you provide the template and all logic where drawingpad is being used,
and your package.json (strip private data of course)

**Comment by JorgeHawkins** [comment]
Sorry, I meant "require", not "include". 

This is the only part where the drawingpad is required. But it will crash the entire app on minimizing after loading.

`var Page;

function sciLoad(args){

    Page = args.object;

}

function deleteSign(){

    Page.getViewById("drawingPad").clearDrawing();

}

function turnOffMove(){

    Page.getViewById("proceedBut").isUserInteractionEnabled = false;

    Page.getViewById("resetField").isUserInteractionEnabled = false;

    Page.getViewById("loading-block").style.opacity = 1;

}

function turnOnMove(){

    Page.getViewById("proceedBut").isUserInteractionEnabled = true;

    Page.getViewById("resetField").isUserInteractionEnabled = true;

    Page.getViewById("loading-block").style.opacity = 0;

}

function saveSign(){

    var ImageModule = require("ui/image");

    var ImageSourceModule = require("image-source");

    SIGNATURE = "";

    var drawingPad = require("nativescript-drawingpad").DrawingPad;

    var field = Page.getViewById('drawingPad');      

    field.getTransparentDrawing().then(function(data){

        //console.log("DATA: " + data);

        var image = ImageSourceModule.fromNativeSource(data);

        SIGNATURE = image.toBase64String('png');

        //console.dir(LOG_CREDENTIALS);

        var xhttp = new XMLHttpRequest(); 

        turnOffMove();

        var timeoutOp = setTimeout(function(){

            turnOnMove();

        }, 7000);

        try {

            xhttp.onreadystatechange = function(){

                //console.log(this.readyState + "/" + this.status);

                if (this.readyState == 4){

                    if(this.status == 200){

                        if(this.responseText === "SUCCESS"){

                            var frameModule = require("ui/frame");

                            var topmost = frameModule.topmost();

                            var topmostNext = {moduleName: "views/sci-welcome/sci-welcome", clearHistory : true, backstackVisible: false, animated : true, transition : {name : "slide", duration : 800, curve : "easeOut", backstackVisible: false}};

                            clearTimeout(timeoutOp);

                            setTimeout(function(){

                                return topmost.navigate(topmostNext);

                            }, 3000);

                        } else {

                            var toast = require("nativescript-toast");

                            var toastError = toast.makeText("No se ha podido actualizar la firma.\nRevise su conectividad a Internet.").show();

                            clearTimeout(timeoutOp);

                            turnOnMove();

                        }

                    } else {

                        qrCode.stop();

                        var toast = require("nativescript-toast");

                        var toastError = toast.makeText("No se ha podido almacenar la firma. Conéctese a Internet.").show();

                        clearTimeout(timeoutOp);

                        turnOnMove();

                    }

                } 

            }

            xhttp.open("POST", stripped for security, true);
            xhttp.send((stripped for security));

        } catch(err){


            var toast = require("nativescript-toast");

            var toastError = toast.makeText("No se ha podido almacenar la firma. Conéctese a Internet.").show();

            clearTimeout(timeoutOp);

            turnOnMove();

        }

    }).catch(function(){

        var dialogs = require("ui/dialogs");
        dialogs.confirm({

            title: "Campo de firma vacío",
            message: "¡El campo de firma no puede estar vacío!",
            okButtonText: "ENTENDIDO"

        });

    });

}

exports.saveSign = saveSign;
exports.deleteSign = deleteSign;
exports.sciLoad = sciLoad;`


This is my `package.json`.

`{
  "dependencies": {
    "nativescript-android-utils": "^1.0.2",
    "nativescript-background-http": "^3.1.0",
    "nativescript-barcodescanner": "^2.6.1",
    "nativescript-camera": "^3.1.2",
    "nativescript-dom": "^2.0.0",
    "nativescript-drawingpad": "^3.0.3",
    "nativescript-geolocation": "^3.0.1",
    "nativescript-local-notifications": "^2.0.3",
    "nativescript-master-technology": "^1.1.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-photoviewer": "^1.2.0",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-sound": "^1.0.4",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.6",
    "tns-core-modules": "^4.1.0"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11"
  },
  "author": "Jorge Hawkins"
}
`
