### ISSUE TITLE
iOS Xcode Build Fails: "linker command failed"...framework not found SignatureView

### ISSUE THREAD

**Issue by NL33** [bradmartin/nativescript-drawingpad#45]
I have downloaded the plugin and successfully used it on the emulator for iOS. I have also been able to use it successfully locally on my device using "tns run ios".

However, if I try to run it through xcode (going into xcode, selecting the app's build, selecting my attached device, and then hitting "play"), I keep getting the error:

`"linker command failed with exit code 1"`

I also get the warning: 
```
directory not found for option '......../Build/Products/iphoneos/SignatureView'
ld: framework not found SignatureView
```

I also get this warning when running "tns run ios" (though the build is able to succeed there, despite the warning).

Is there a way to cure the warning (which might hopefully cure the error)?

**Comment by NL33** [comment]
Bump. Any ideas? I also get these warnings when running $ tns run ios:
warning: 
      ```
comparison of function 'UIGraphicsBeginImageContextWithOptions' not equal to a null pointer is always true
      [-Wtautological-pointer-compare]
    if (UIGraphicsBeginImageContextWithOptions != NULL) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
.../ios/Pods/SignatureView/Source/SignatureView.m:205:9: note: 
      prefix with the address-of operator to silence this warning
    if (UIGraphicsBeginImageContextWithOptions != NULL) {
        ^

```

**Comment by bradmartin** [comment]
the mention of 

```objc
comparison of function 'UIGraphicsBeginImageContextWithOptions' not equal to a null pointer is always true
[-Wtautological-pointer-compare]
if (UIGraphicsBeginImageContextWithOptions != NULL) {
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ~~~~
.../ios/Pods/SignatureView/Source/SignatureView.m:205:9: note:
prefix with the address-of operator to silence this warning
if (UIGraphicsBeginImageContextWithOptions != NULL) {
``` 

is a warning for the iOS source. You can ignore it or fork the pod source and fix and we can use that fork or you can PR a fix to the main repo of the pod with the fix.

I'm unable to duplicate your build issue however, let me know if you still run into this and we can see about a repro project.

**Comment by NL33** [comment]
Thanks, @bradmartin. With updating to NS 5.0+, I do continue to have warnings like mentioned earlier (basically, variations of "Signature View not found"), but I have not had the build issues.
