### ISSUE TITLE
IOS SignatureView not found

### ISSUE THREAD

**Issue by leonable** [bradmartin/nativescript-drawingpad#54]
I keep hitting this issue and the whole page not rendering.

CONSOLE ERROR file:///app/tns_modules/@angular/core/bundles/core.umd.js:5907:24: ERROR Error: Uncaught (in promise): ReferenceError: Can't find variable: SignatureView

Anyone else facing this in IOS that can help?

**Comment by bradmartin** [comment]
Not 100% clear based on that error, but can you be sure to enable `skipLibCheck` in your project's `tsconfig.json` as you typically don't want to analyze node_modules anyway.
