### ISSUE TITLE
Image to base64

### ISSUE THREAD

**Issue by huehnerhose** [bradmartin/nativescript-drawingpad#7]
Hi,

sorry but I am really stuck here. I want to use this plugin for saving a signature to my backend. But I am simply not capable to find a solution to get some "useful" data from `getDrawing()`.
At the moment I use iOS and get a UIImage Instance. I would love to "convert" the image data to some base64 (png, or whatever) string and send it to my server. 

I tried someting like:
```
var ImageModule = require("ui/image");
var ImageSourceModule = require("image-source");

elements.drawingpad.getDrawing().then(function(a){
	var image = ImageSourceModule.fromNativeSource( a );
	api.post("sign", image.toBase64String());
});
```

I also tried to post simply `a` like seen in your demo stuff. 

I would really love to see a demo of how to get my hands on the "image data" itself. 

thanks!

**Comment by huehnerhose** [comment]
Thanks to @bradmartin I found the solution:
    var image = ImageSoruceModule.fromNativeSource(a);
    var base64 = image.toBase64('png');

Thanks for that plugin!

**Comment by leocrawf** [comment]
If you are going to share a working piece of work make sure to copy and paste it. The correct code is posted here: https://github.com/bradmartin/nativescript-drawingpad/issues/15
