### ISSUE TITLE
Issues with web pack build

### ISSUE THREAD

**Issue by hypery2k** [bradmartin/nativescript-drawingpad#9]
When trying to use in nativescript-angular app with webpack enabled I'm getting the following error:
```
09-19 12:44:06.025 19533 19533 E AndroidRuntime: TypeError: Cannot read property 'gcacace' of undefined
09-19 12:44:06.025 19533 19533 E AndroidRuntime: File: "/data/data/de.sample.app/files/app/bundle.js, line: 95825, column: 30
```
Any ideas?

I check a similar [issue](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/41), but it didn't helped

**Comment by bradmartin** [comment]
Yes a few ideas. Let me get back to you later when I get to the office.

**Comment by bradmartin** [comment]
First idea is this
https://bradmartin.net/2016/07/20/ahhh-this-nativescript-plugin-doesnt-work/
and second idea is a tsconfig setting to ignore errors. There is one for
errors and one that resolves some webpack build. Think that's been reported
and fixed before though.

**Comment by bradmartin** [comment]
noEmitOnError is the other flag, I forget the setting here but should be in
the config file. On my phone now or I'd check for you. Let me know if any
of that helps

**Comment by bradmartin** [comment]
@hypery2k - was this solved or you need help?

**Comment by hypery2k** [comment]
not completely, but I think it's more an native script issue, than your plugin, see https://github.com/NativeScript/NativeScript/issues/2760
